# Generated by Django 5.0 on 2024-01-18 20:02

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Library',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='اسم المكتبة')),
                ('desc', models.TextField(blank=True, null=True, verbose_name='مواصفات المكتبة/عنوانها')),
            ],
            options={
                'verbose_name': 'مكتبة',
                'verbose_name_plural': 'المكاتب',
            },
        ),
        migrations.CreateModel(
            name='LibraryCharges',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(verbose_name='قيمة الفاتورة')),
                ('descri', models.TextField(blank=True, verbose_name='سبب الفاتورة')),
                ('time_ad', models.DateField(default=datetime.datetime.now, editable=False, verbose_name='وقت اضافة الفاتورة')),
                ('library', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='lib.library', verbose_name='المكتبة')),
            ],
            options={
                'verbose_name': 'فاتورة المكتبة',
                'verbose_name_plural': 'فواتير المكتبات',
            },
        ),
    ]
