# Generated by Django 5.0 on 2024-01-13 14:19

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('config', '0002_alter_cashout_options_alter_coursegroup_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='اسم الطالب/ة')),
                ('phone_number', models.CharField(max_length=255, verbose_name='رقم الهاتف')),
                ('paid', models.IntegerField(blank=True, default=0, verbose_name='المبلغ الذي تم دفعة')),
                ('have_debt', models.BooleanField(default=True, verbose_name='مدين؟')),
                ('voucher', models.FloatField(blank=True, default=0, verbose_name='الخصومات')),
                ('time_added', models.DateField(default=datetime.datetime.now, verbose_name='وقت اضافة الطالب')),
                ('myqr', models.ImageField(blank=True, editable=False, upload_to='clientqrcodes')),
                ('payment_method', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='config.paymentmethod', verbose_name='طريقة الدفع')),
            ],
            options={
                'verbose_name': 'الطالب/ة',
                'verbose_name_plural': 'الطلاب',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=255, verbose_name='اسم الدرس')),
                ('start_date', models.DateField(default=datetime.datetime.now, verbose_name='بداية الكورس')),
                ('end_date', models.DateField(default=datetime.datetime.now, verbose_name='نهاية الكورس')),
                ('cost_forone', models.FloatField(blank=True, default=0, verbose_name='سعر الدرس للفرد الواحد')),
                ('Voucher', models.FloatField(blank=True, default=0, verbose_name=' تكلفة الدرس على الاستاذ')),
                ('Day_per_week', models.ManyToManyField(blank=True, related_name='Days', to='config.days', verbose_name='كم يوما فلأسبوع')),
                ('groups', models.ManyToManyField(blank=True, related_name='Group', to='config.coursegroup', verbose_name='المجموعات')),
            ],
            options={
                'verbose_name': 'الدرس',
                'verbose_name_plural': 'الدروس',
            },
        ),
        migrations.CreateModel(
            name='ClintCourses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Atten', models.TextField(blank=True, null=True)),
                ('date_for', models.DateField(default=datetime.datetime.now, editable=False)),
                ('the_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Thoth.client')),
                ('the_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Thoth.course', verbose_name='اسم الدرس')),
            ],
            options={
                'verbose_name': 'درس الطالب',
                'verbose_name_plural': 'دروس الطلاب',
            },
        ),
        migrations.CreateModel(
            name='ClientScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_score', models.IntegerField(verbose_name='درجة الطالب/ة')),
                ('max_score', models.IntegerField(verbose_name='الدرجة النهائية')),
                ('the_client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Thoth.client')),
                ('the_course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Thoth.course', verbose_name='الدرس')),
            ],
            options={
                'verbose_name': 'نتيجة الطالب',
                'verbose_name_plural': 'نتائج الطلاب',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='اسم الموظف')),
                ('Person_identf', models.CharField(blank=True, default=' ', max_length=255, null=True, verbose_name='الرقم القومي')),
                ('EDU_state', models.CharField(blank=True, default=' ', max_length=300, null=True, verbose_name='المستوى التعليمي')),
                ('address', models.CharField(blank=True, default=' ', max_length=300, null=True, verbose_name='العنوان')),
                ('img', models.ImageField(blank=True, upload_to='EMP Pic', verbose_name=' ')),
                ('cur_sallary', models.FloatField(verbose_name='راتب شهري')),
                ('Date_of_join', models.DateField(default=datetime.datetime.now, verbose_name='تاريخ الانضمام')),
                ('state_of_marrieg', models.CharField(choices=[('Married', 'متزوج'), ('Single', 'اعزب'), ('Divorced', 'مطلق'), ('Widower', 'ارمل')], max_length=300, verbose_name='الحالة الاجتماعية')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='رقم الهاتف')),
                ('phone_number_eme', models.CharField(blank=True, max_length=20, null=True, verbose_name='رقم الهاتف فحالة طارئة')),
                ('more', models.CharField(default='المزيد', editable=False, max_length=10)),
                ('job_postition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='config.jobposition', verbose_name='المنصب الوظيفي')),
            ],
            options={
                'verbose_name': 'موظف',
                'verbose_name_plural': 'الموظفين',
            },
        ),
        migrations.CreateModel(
            name='Deduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('The_amount', models.IntegerField(verbose_name='المقدار')),
                ('the_reson', models.TextField(blank=True, null=True, verbose_name='السبب')),
                ('Emp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Thoth.employee')),
            ],
            options={
                'verbose_name': 'خصم من الموظف',
                'verbose_name_plural': 'خصومات الموظفين',
            },
        ),
        migrations.CreateModel(
            name='Absent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('how_many_days', models.IntegerField(verbose_name='عدد الأيام')),
                ('Reson', models.TextField(blank=True, default=' ', verbose_name='السبب')),
                ('Emp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Thoth.employee')),
            ],
            options={
                'verbose_name': 'غياب الموظف',
                'verbose_name_plural': 'غيابات الموظف',
            },
        ),
        migrations.CreateModel(
            name='Parentsphonenumbers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='اسم صاحب الرقم')),
                ('phone_number', models.CharField(max_length=255, verbose_name='رقم الهاتف')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Thoth.client')),
            ],
            options={
                'verbose_name': 'رقم ولي الأمر',
                'verbose_name_plural': 'ارقام أولياء الأمور',
            },
        ),
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('The_amount', models.IntegerField(verbose_name='المقدار')),
                ('the_reson', models.TextField(blank=True, null=True, verbose_name='السبب')),
                ('img', models.ImageField(blank=True, upload_to='', verbose_name='صورة لشهادة(اختياري)')),
                ('Emp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Thoth.employee')),
            ],
            options={
                'verbose_name': 'جائزة للموظف',
                'verbose_name_plural': 'جوائز الموظفين',
            },
        ),
        migrations.CreateModel(
            name='vacation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vacation_type', models.CharField(choices=[('Sick leave', 'مرضي'), ('weekends', 'اعتيادي')], max_length=300, verbose_name='نوع الاجازة')),
                ('how_many_days', models.IntegerField(default=0, verbose_name='عدد ايام الاجازة')),
                ('Emp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Thoth.employee')),
            ],
            options={
                'verbose_name': 'اجازة الموظف',
                'verbose_name_plural': 'اجازات الموظفين',
            },
        ),
    ]
