# Generated by Django 5.0 on 2024-01-15 04:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Thoth', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='payment_method',
        ),
        migrations.RemoveField(
            model_name='course',
            name='groups',
        ),
        migrations.AddField(
            model_name='client',
            name='courses',
            field=models.ManyToManyField(blank=True, to='Thoth.course', verbose_name='الدروس'),
        ),
        migrations.AlterField(
            model_name='course',
            name='end_date',
            field=models.DateField(default=datetime.datetime.now, verbose_name='نهاية الدرس'),
        ),
        migrations.AlterField(
            model_name='course',
            name='start_date',
            field=models.DateField(default=datetime.datetime.now, verbose_name='بداية الدرس'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='job_postition',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='المنصب الوظيفي'),
        ),
    ]
