# Generated by Django 5.0 on 2024-01-17 01:54

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Thoth', '0002_remove_client_payment_method_remove_course_groups_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientCourseRel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rel_date', models.DateField(default=datetime.datetime.now, editable=False)),
                ('attend', models.TextField(blank=True, editable=False, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Thoth.client', verbose_name='الطالب')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Thoth.course', verbose_name='الدرس')),
            ],
            options={
                'verbose_name': 'درس الطالب',
                'verbose_name_plural': 'دروس الطالب',
            },
        ),
        migrations.DeleteModel(
            name='ClintCourses',
        ),
    ]
