# Generated by Django 5.0 on 2024-01-17 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Thoth', '0003_clientcourserel_delete_clintcourses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='courses',
        ),
    ]
