# Generated by Django 5.0 on 2024-01-13 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cashout',
            options={'verbose_name': 'تكلفة', 'verbose_name_plural': 'تكاليف المكان'},
        ),
        migrations.AlterModelOptions(
            name='coursegroup',
            options={'verbose_name': 'فئة', 'verbose_name_plural': 'الفئات'},
        ),
        migrations.AlterModelOptions(
            name='jobposition',
            options={'verbose_name': 'منصب وظيفي', 'verbose_name_plural': 'المناصب الوظيفية'},
        ),
        migrations.AlterModelOptions(
            name='paymentmethod',
            options={'verbose_name': 'طريقة الدفع', 'verbose_name_plural': 'طرق الدفع'},
        ),
        migrations.AlterField(
            model_name='cashout',
            name='Amount',
            field=models.IntegerField(verbose_name='مقدار السعر'),
        ),
        migrations.AlterField(
            model_name='cashout',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='الوصف'),
        ),
        migrations.AlterField(
            model_name='cashout',
            name='time_added',
            field=models.DateField(auto_now_add=True, verbose_name='وقت الاضافة'),
        ),
        migrations.AlterField(
            model_name='coursegroup',
            name='name',
            field=models.CharField(max_length=255, verbose_name='اسم الفئة'),
        ),
        migrations.AlterField(
            model_name='jobposition',
            name='job_title',
            field=models.CharField(max_length=300, verbose_name='اسم المنصب الوظيفي'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='Paymentname',
            field=models.CharField(max_length=255, verbose_name='اسم الطريقة'),
        ),
    ]
