# Generated by Django 5.0 on 2024-01-15 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Thoth', '0002_remove_client_payment_method_remove_course_groups_and_more'),
        ('config', '0002_alter_cashout_options_alter_coursegroup_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CourseGroup',
        ),
        migrations.DeleteModel(
            name='JobPosition',
        ),
    ]
