# Generated by Django 5.0 on 2024-01-17 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0003_delete_coursegroup_delete_jobposition'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PaymentMethod',
        ),
    ]
